import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from "react";


export default function Home() {

    const handleForm = require('../logic/handleForm.js')
    const [form, setForm] = useState({
        prenom: null,
        nom: null,
        email: null,
        password: null,
    })

    const [fillForm, setFillForm] = useState(false)
    const [validatedForm, setValidatedForm] = useState(false)

    function submitForm(e) {
        e.preventDefault()
        console.log(form)
        if(form.prenom === null || form.nom === null || form.email === null || form.password === null) {
            setFillForm(true)
        }
        if(handleForm.handleEmail(form.email)){
            if(handleForm.handlePassword(form.password)){
                setFillForm(false)
                setValidatedForm(true)
            }
        }
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Rendu <span>Mathias Gilles, Sosthène Fruchard et Jules Dayaux</span>
                </h1>
                <div className={styles.grid}>
                    <form className={styles.form} onChange={(e) => setForm({
                        ...form,
                        [e.target.name]: e.target.value
                    })}>
                        <label>Prenom</label>
                        <br/>
                        <input type="text" name="prenom"/>
                        <br/>
                        <br/>
                        <label>Nom</label>
                        <br/>
                        <input type="text" name="nom"/>
                        <br/>
                        <br/>
                        <label>Email</label>
                        <br/>
                        <input type="text" name="email"/>
                        <br/>
                        <br/>
                        <label>Mot de passe</label>
                        <br/>
                        <input type="text" name="password"/>
                        <br/>
                        <button onClick={submitForm}>Soumettre le formulaire</button>
                        {fillForm && <div>Remplis le formulaire complètement stp</div>}
                        {validatedForm && <div>Votre formulaire est validé !</div>}
                    </form>
                </div>
            </main>
            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}
