name: deploy dev to vercel

on:
  push:
    branches:
      - dev

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: pages/
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.0
        with:
          prettier_options: --write ./*.{js,md}
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
      - uses: actions/checkout@v2
        with:
          script: |
            npm install
            npm run test
  deploy:
    needs: [ eslint, prettier, testing ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-project-id: ${{ secrets.PREPROD_VERCEL_PROJECTID}}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
