name: deploy dev to vercel

on:
  push:
    branches:
      - dev

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        uses: actions/checkout@v2
        with:
          script: |
            npm ci
            npm run test
  eslint:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: actions/checkout@v2
        with:
          script: |
            npm run lint
  prettier:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.0
        with:
          prettier_options: --write ./*.{js,md}
  doc:
    needs: [ eslint, prettier ]
    runs-on: ubuntu-latest
    steps:
      - name: Create documentation
        uses: actions/checkout@v2
        with:
          script: npm run jsdoc
  deploy:
    needs: doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-project-id: ${{ secrets.PREPROD_VERCEL_PROJECTID}}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
