name: deploy nexturl to vercel

on:
  pull_request:
    branches:
      - dev

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.0
        with:
          prettier_options: --write app/*.{js,md}
  deploy:
    needs: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-project-id: ${{ secrets.PREPROD_VERCEL_PROJECTID}}
