name: test, lint and document pull requests

on:
  pull_request_target:
    types:
      - [ opened, labeled ]
    branches:
      - 'dev'

jobs:
  test:
    if: ${{ github.event.label.name == 'test' || github.event.label.name == 'all-pr'}}
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        uses: actions/checkout@v2
        with:
          script: |
            npm ci
            npm run test
  eslint:
    if: ${{ github.event.label.name == 'lint' || github.event.label.name == 'all-pr' }}
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: actions/checkout@v2
        with:
          script: |
            npm run lint
  prettier:
    if: ${{ github.event.label.name == 'lint' || github.event.label.name == 'all-pr' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.0
        with:
          prettier_options: --write ./*.{js,md}
  docs:
    if: ${{ github.event.label.name == 'docs' || github.event.label.name == 'all-pr'}}
    runs-on: ubuntu-latest
    steps:
      - name: Create documentation
        uses: actions/checkout@v2
        with:
          script: npm run jsdoc