name: test, lint and document pull requests

on:
  pull_request_target:
    types:
      - [ opened, labeled ]
    branches:
      - 'dev'

jobs:
  test:
    if: ${{ github.event.label.name == 'test' || github.event.label.name == 'all-pr'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
          cache-dependency-path: api/package-lock.json
      - run: |
        npm ci
        npm run test
  lint:
    if: ${{ github.event.label.name == 'lint' || github.event.label.name == 'all-pr' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
        npm ci
        npm run lint
  docs:
    if: ${{ github.event.label.name == 'docs' || github.event.label.name == 'all-pr'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
        npm run jsdoc